version: 2.1
orbs:
  node: circleci/node@3.0.0
parameters:
  url:
    type: string
    default: ""
    description: "ACCELQ URL"
  tenant:
    type: string
    default: ""
    description: "ACCELQ Tenant Code"  
  project-name:
    type: string
    default: ""
    description: "ACCELQ Project Name"
  job-id:
    type: string
    default: ""
    description: "ACCELQ CI Job Id"
  user:
    type: string
    default: ""
    description: "ACCELQ User Id"
  password:
    type: string
    default: ""
    description: "ACCELQ User Password"
  agent-name:
    type: string
    default: ""
    description: "ACCELQ Agent Name"
  runparams:
    type: string
    default: ""
    description: "ACCELQ Run Params example(Customer Name=John Todd & Customer Id=232)"
jobs:
  build-accelq:
    docker:
    - image: 'cimg/base:stable'
    steps:
    - run:
        name: ACCELQ CI-CD Job
        command: |
          wget https://accelq.s3.amazonaws.com/releases/plugins/latest/aq-vsts-azure-plugin-latest.tar.gz
          tar xvzf aq-vsts-azure-plugin-latest.tar.gz
          cd aq-vsts-azure-plugin-latest
          ls -al
          npm install
          node app.js  --url << pipeline.parameters.url >> --tenant << pipeline.parameters.tenant >> --project << pipeline.parameters.project-name >> --user << pipeline.parameters.user >> --password << pipeline.parameters.password >> --jobid << pipeline.parameters.job-id >> --agent << pipeline.parameters.agent-name >> --runparams << pipeline.parameters.runparams >>

workflows:
  accelq-ci-cd:
    jobs:
      - build-accelq
